### ISSUE TITLE
centos部署时pyppeteer浏览器无法启动问题

### ISSUE THREAD

**Issue by sswest** [coder-fly/douyin-signature#11]
我尝试在centos、ubuntu和mac部署签名服务，但只有mac成功了，centos和ubutun都抛出同一段错误:
```shell
Traceback (most recent call last):
  File "chrome.py", line 40, in <module>
    loop.run_until_complete(connect_chrome(path))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "chrome.py", line 20, in connect_chrome
    browser = await launch(headless=False, args=["--no-sandbox", "--disable-gpu"], executablePath=path)
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/launcher.py", line 305, in launch
    return await Launcher(options, **kwargs).launch()
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/launcher.py", line 166, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "/usr/local/lib/python3.6/site-packages/pyppeteer/launcher.py", line 225, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:
```
一开始我认为是chrome的问题，当我解决了chrome依赖问题和尝试多个chrome版本依然报错后，我直接用nmp安装了puppeteer，发现浏览器能够正常启动，所以现在更倾向认为是pyppeteer本身的问题，然而我并没有找到相关的解决方案，请问一下作者有遇到过这个问题吗?
另外我也想尝试通过node.js调用puppeteer，代码如下:
```javascript
const puppeteer = require('puppeteer');
  

(async () => {
    const webdriver_js = "() => Object.defineProperties(navigator,{webdriver:{get: () => false}})";
    const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox']
    });
    const page = await browser.newPage();
    await page.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36");
    await page.goto('http://127.0.0.1:8010/');
    await page.evaluate(webdriver_js);
    const sign = await page.evaluate('generateSignature', 'i)6a6i2spjks!i#tfus"0y\u02a1g,&qnfme', '86560737726');
    console.log(sign);
    await browser.close();
})();
```
但不管我向generateSignature传入或者不传入参数，使用node调用后打印的结果都是空字典
```shell
[root@iZwz998jigq7l0lwy0wmbyZ ~]# node sign.js 
{}
```

**Comment by sswest** [comment]
很神奇一件事
当我把代码从
```python
browser = await launch(headless=False, args=["--no-sandbox"])
```
改成
```python
browser = await launch({'headless': True, 'args': ['--no-sandbox']})
```
它居然就可以在Centos上正常工作了,,十分懵圈
