### ISSUE TITLE
JS报错

### ISSUE THREAD

**Issue by llongday** [coder-fly/douyin-signature#2]
pyppeteer.errors.ElementHandleError: Evaluation failed: TypeError: Cannot set property '0' of undefined
    at c (http://127.0.0.1:5001/static/douyin.js:122:43)
    at c (http://127.0.0.1:5001/static/douyin.js:130:75)
    at r (http://127.0.0.1:5001/static/douyin.js:29:24)
    at Object.e [as sign] (http://127.0.0.1:5001/static/douyin.js:201:44)
    at generateSignature (http://127.0.0.1:5001/static/douyin.js:244:14)
运行程序出现这种错误,不知道怎么处理了

**Comment by coder-fly** [comment]
更新了tac，貌似没有这个错误了。
